name: Package
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Publish to NuGet.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'

      - name: Set environment variables
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set version
        run: sed -i 's/${RELEASE_VERSION}/'${{env.RELEASE_VERSION}}'/g' DoliteTemplate.nuspec

      - name: Create nuget package
        run: nuget pack DoliteTemplate.nuspec -NoDefaultExcludes
        
      - name: Publish nuget package
        run: nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
